---
# tasks file for mywebrole3
- name: install webserver
  apt: 
    name: apache2
    state: present
    notify: restartwebserver

- name:  copy index file into node 
  template:
      src: templates/index.j2
      dest: var/www/html/index.html
  notify: restartwebserver    