---
- hosts: 172.31.38.41
  become: yes
  tasks: 
  - include_tasks: mytestfile.yml

  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restarted
  - name: i want to copy file into ansible node
    template:
       src: myindex.j2
       dest: /var/www/html/index.html    
    notify: restarted

  handlers:
   - name: restarted
     service:
        name: apache2
        state: restarted     
        

