---
- hosts: 172.31.10.150
  become: yes
  tasks:
  - name: install tree
    apt:
      name: tree
      state: present

  - name: install git
    apt:
      name: install git
      state: present

  - name: install wget
    apt:
      name: wget
      state: present
                