---
- hosts: 172.31.10.150
  become: yes
  tasks:
  - name: install tree
    apt:
      name: tree
      stateee: present
    tags: tree
  - name: install git
    apt:
      name: git
      state: present
    tags: git
  - name: install wget
    apt:
      name: wget
      state: present
    tags: wget